logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  rabbitmq:
    addresses: porpoise-01.rmq.cloudamqp.com
    username: zjilarls
    password: 7M_TAIe7B_70M-USUlpHwqo6e3NbALqt
    virtual-host: zjilarls